### ISSUE TITLE
Stopped working for version 3.0.0

### ISSUE THREAD

**Issue by pedro-w** [transitive-bullshit/random#22]
I have some JS code, run in node, which was working in 2.2 and now is not. Previously I had:
```
const random = require('random')
...
const power = random.normal(27.545, 2.182)
...
const v = power()
```
Now I get
```
Uncaught TypeError: random.normal is not a function
```
So I changed to
```
const random = require('random').default
```
but now
```
> power()
Uncaught TypeError: Cannot read property 'next' of undefined
    at Random.next (D:\temp\ser\node_modules\random\dist\random.js:56:31)
    at exports.default (D:\temp\ser\node_modules\random\dist\distributions\normal.js:9:24)
```
so I had to add
```
random.use(Math.random)
```
as part of the initialization.

Please could you advise: Am I doing the right thing? It would be great if this could make it into the docs. I assume this all works as per the docs in Typescript but I am not allowed to use that at the moment.

**Comment by Vladi4-gh** [comment]
Same
![image](https://user-images.githubusercontent.com/20474669/109517874-c4408300-7aba-11eb-9111-1fd1c1a744d5.png)

**Comment by agmoss** [comment]
This appears to be an issue with the TS to CJS configuration. Furthermore the docs are out of date to 3.0.0. 

 To use 3.0.0 in cjs 

```javascript 
const random = require('random').default

random.use(Math.random)
const power = random.normal(27.545, 2.182)
const v = power()

```

I will look for a remedy

**Comment by transitive-bullshit** [comment]
@agmoss we should definitely default to `Math.random` as the RNG.

**Comment by transitive-bullshit** [comment]
@vegeta897 @pedro-w @Vladi4-gh would you mind updating to `v3.0.1` and seeing if that fixes your issue?

```js
const random = require('random')

const dist = random.normal(27.545, 2.182)
const v = dist()
```

**Comment by pedro-w** [comment]
@transitive-bullshit yes, from a quick look it seems to be working well now. Thanks very much for the speedy response.

**Comment by Vladi4-gh** [comment]
Same
![image](https://user-images.githubusercontent.com/20474669/109551529-bd793680-7ae1-11eb-921d-c515584a4af2.png)

**Comment by transitive-bullshit** [comment]
Thanks, guys!

**Comment by vegeta897** [comment]
Thank you for the mention @transitive-bullshit, looks like this worked. My tests still failed because `random.int()` no longer works with a single argument (max with an implied 0 min) or with no arguments (implied 0-1) but I'm happy to adapt to this if it was intended.

**Comment by transitive-bullshit** [comment]
@vegeta897 this should now be fixed in `3.0.3` thanks to @agmoss 💯

**Comment by vegeta897** [comment]
💯💯💯 thank you @agmoss and @transitive-bullshit
